name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install Python dependencies

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -p "test_*.py"  # Run all tests in the tests directory

  build-and-test:
    name: Build Docker Image and Test Application
    runs-on: ubuntu-latest
    needs: test  # Ensure tests pass before building the Docker image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t receipt-processor .  # Build the Docker image

      - name: Run Docker container
        run: |
          docker run --name recpt -d -p 5002:5002 receipt-processor  # Run the container in detached mode

      - name: Wait for application to start
        run: |
          sleep 10  # Wait for the application to start

      - name: Test API endpoints
        run: |
          # Test POST /receipts/process
          POST_RESPONSE=$(curl -X POST -H "Content-Type: application/json" -d @test_receipts/valid_rpt1.json http://localhost:5002/receipts/process)
          echo "POST Response: $POST_RESPONSE"

          # Extract receipt ID from the POST response
          RECEIPT_ID=$(echo $POST_RESPONSE | jq -r '.id')
          echo "Receipt ID: $RECEIPT_ID"

          # Test GET /receipts/{id}/points
          GET_RESPONSE=$(curl -X GET http://localhost:5002/receipts/$RECEIPT_ID/points)
          echo "GET Response: $GET_RESPONSE"

          # Validate the responses
          if [[ -z "$RECEIPT_ID" ]]; then
            echo "Error: Receipt ID not found in POST response"
            exit 1
          fi

          if [[ -z "$GET_RESPONSE" ]]; then
            echo "Error: No response from GET /receipts/{id}/points"
            exit 1
          fi

          echo "API tests passed successfully!"

      - name: Stop and remove Docker container
        run: |
          docker stop recpt  # Stop the container
          docker rm recpt   # Remove the container
